# Generated by Django 4.2.8 on 2024-01-19 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(blank=True, max_length=100, null=True, verbose_name='Место')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время')),
                ('action', models.CharField(max_length=100, verbose_name='Действие')),
                ('is_pleasant_habit', models.BooleanField(default=False, verbose_name='Признак приятной привычки')),
                ('frequency', models.PositiveIntegerField(blank=True, default=1, null=True, verbose_name='Периодичность')),
                ('reward', models.CharField(blank=True, max_length=100, null=True, verbose_name='Вознаграждение')),
                ('time_to_complete', models.PositiveIntegerField(blank=True, default=120, null=True, verbose_name='Время на выполнение')),
                ('is_public', models.BooleanField(default=False, verbose_name='Признак публичности')),
                ('related_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habits.habit', verbose_name='Связанная привычка')),
            ],
            options={
                'verbose_name': 'Привычка',
                'verbose_name_plural': 'Привычки',
            },
        ),
    ]
